name: Publish to PyPI
on:
  push:
    branches:
      - main
env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
    - name: Build 
      run: poetry build 
    - name: Check PYPI_TOKEN
      run: echo $PYPI_TOKEN
    - name: Publish to PyPI
      run:  poetry publish --username __token__ --password $PYPI_TOKEN

      
 